"""Update to add request admin

Revision ID: 16750e03fb51
Revises: c6639d043fbd
Create Date: 2024-08-13 17:17:53.935685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16750e03fb51'
down_revision = 'c6639d043fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requesting_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('requesting_admin')

    # ### end Alembic commands ###
